name: 'Auto Tag Commit'
author: 'matthieuEv'
description: 'An easy way to manage tag using Commits name for Releases in a project '
branding:
  icon: 'tag'
  color: 'blue'

runs:
  using: 'node20'
  main: 'index.js'
