name: 'Tag Creation'
author: 'matthieuEv'
description: 'This action creates a new tag based on the commit message.'
branding:
  icon: 'tag'
  color: 'blue'

runs:
  using: 'node16'
  main: 'index.js'
